global:
  scrape_interval: 5s  # Collect metrics every 5 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrape Prometheus itself (within the container)

  - job_name: 'spring-boot-app'  # Scrape your Spring Boot app via ngrok
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['0009-2401-4900-8899-a77-6d96-1948-b224-eccb.ngrok-free.app'] # **REPLACE THIS WITH YOUR ACTUAL NGROK URL**
        labels:
          environment: 'development'  # Optional label
